### ISSUE TITLE
GitHub sign on ask to give permission to u8sand 

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/FAIRshake#145]
It is better to remove this option for now, or have it set up that the request is not showing a personal account

**Comment by u8sand** [comment]
To resolve this, someone with permissions in the organization should register the OAuth information at:

https://github.com/organizations/[ORGNAME]/settings/applications

Logo: 
![image](https://user-images.githubusercontent.com/1341861/108407346-a0935800-71f1-11eb-892d-55dd7237553b.png)

application name: fairshake.cloud
homepage url: https://fairshake.cloud/
application description: A System to Evaluate Digital Objects for FAIRness.
authorization callback URL: https://fairshake.cloud/accounts/github/login/callback/

This will result in some secret tokens which should be passed to me securely..

**Comment by u8sand** [comment]
It is also important to note that we have the same challenge with email, we will need to determine a SMTP server and account that can be used instead of my own..

**Comment by u8sand** [comment]
This is fixed for github. Also i found out github has a way to transfer the existing application preserving all settings which is nice.

I'll also look into associating the oauth for globus & orcid.
