### ISSUE TITLE
Metric 17 in fairmetrics needs to be deleted

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/FAIRshake#147]
During a demo, the user entered a new metric to the fairmetrics rubric. That new metric needs to be disassociated from the universal fairmetrics. It is possible that the user already delete it.

**Comment by u8sand** [comment]
FAIRmetrics only has 16 metrics as far as I can tell
![image](https://user-images.githubusercontent.com/1341861/108407863-4fd02f00-71f2-11eb-960f-eb5303470f64.png)

If this is somewhere else, the url to the metric will help to locate it.

**Comment by AviMaayan** [comment]
It looks like it was removed, so no problem.
