### ISSUE TITLE
Unable to edit project details or assessments 

### ISSUE THREAD

**Issue by RahiNav** [MaayanLab/FAIRshake#167]
I am unable to edit any details for the project I created: https://fairshake.cloud/project/173/
I used the same login when I created the project and associated digital object. However now I am unable edit any details of projects, assessments, etc with the same login.

**Comment by AviMaayan** [comment]
Dear @RahiNav we are looking into fixing this issue. It turns out to be a greater issue that a simple fix. We should be able to tackle it by the end of next week. Best, Avi

**Comment by AviMaayan** [comment]
Dear @RahiNav can you try it again? I just tested the system and it seems to work for me (edit project details and assessments). Best, Avi

**Comment by RahiNav** [comment]
Hi Avi, 
I am still unable to edit the objects I previously created with the same login. 
<img width="1295" alt="Screen Shot 2022-11-07 at 8 31 26 AM" src="https://user-images.githubusercontent.com/89993916/200323027-9e101b2b-ae46-493f-a5bc-dd15b3077cf5.png">
<img width="1295" alt="Screen Shot 2022-11-07 at 8 33 55 AM" src="https://user-images.githubusercontent.com/89993916/200323438-99acb9f8-ad23-4fca-bd45-0111dfe7230d.png">
<img width="1294" alt="Screen Shot 2022-11-07 at 8 34 46 AM" src="https://user-images.githubusercontent.com/89993916/200323610-662d781d-c07a-438e-ae8d-edae1025ed12.png">


If this issue cannot be resolved - I don't mind creating the project and digital objects again. Only someone needs to delete the project (https://fairshake.cloud/project/173/ )and its associated digital objects and assessments.
